"""initial

Revision ID: 20260921_13_41
Revises: 
Create Date: 2026-09-21 13:17:46.071113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260921_13_41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tblm_app_configurations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tblm_impersonation_audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("impersonation_id", sa.Text(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("termination_reason", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tblm_impersonation_audit_impersonation_id"),
        "tblm_impersonation_audit",
        ["impersonation_id"],
        unique=True,
    )
    op.create_table(
        "tblm_impersonation_sandbox_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("value", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tblm_task_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("tag", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "success",
                "failed",
                "interrupted",
                name="task_run_status",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "is_retry", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("log_s3_bucket", sa.Text(), nullable=True),
        sa.Column("log_s3_path", sa.Text(), nullable=True),
        sa.Column("log_s3_url", sa.Text(), nullable=True),
        sa.Column(
            "log_retention_status",
            sa.Enum(
                "local", "archived", "purged", name="task_run_log_retention_status"
            ),
            server_default="local",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tblm_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column(
            "okta_timezone",
            sa.Text(),
            server_default="Asia/Singapore",
            nullable=True,
        ),
        sa.Column("contact_number", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tblm_feature_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("request_email", sa.Text(), nullable=False),
        sa.Column("request_title", sa.Text(), nullable=False),
        sa.Column("request_description", sa.Text(), nullable=True),
        sa.Column("request_business_impact", sa.Text(), nullable=True),
        sa.Column(
            "request_status",
            sa.Enum(
                "New",
                "Under Review",
                "More Info Required",
                "Added to Roadmap",
                "Declined",
                name="feature_request_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "request_priority",
            sa.Enum("Low", "Medium", "High", name="feature_request_priority"),
            nullable=True,
        ),
        sa.Column("request_notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("request_attachments", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tblm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["tblm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "tblm_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tblm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["tblm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tblt_user_sessions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("login_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("logout_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("session_token", sa.Text(), nullable=False),
        sa.Column("previous_session_token", sa.Text(), nullable=True),
        sa.Column(
            "previous_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "login_source",
            sa.Enum("Web", "Mobile", "API", name="login_source"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("browser", sa.Text(), nullable=True),
        sa.Column("browser_version", sa.Text(), nullable=True),
        sa.Column("operating_system", sa.Text(), nullable=True),
        sa.Column("device_type", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Active", "Logged Out", "Expired", name="session_status"),
            nullable=True,
        ),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["tblm_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_index(
        op.f("ix_tblt_user_sessions_user_id"),
        "tblt_user_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tblm_role_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Text(), nullable=False),
        sa.Column("group_name", sa.Text(), nullable=False),
        sa.Column("group_description", sa.Text(), nullable=True),
        sa.Column(
            "permission",
            sa.Enum(
                "GET", "POST", "PUT", "PATCH", "DELETE", name="role_group_permission"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["tblm_roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tblm_user_request_log_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("average_response_time", sa.Float(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("is_cached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["tblt_user_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["tblm_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tblm_user_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tblm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["tblm_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["tblm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "tblt_user_page_access_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_session_id", sa.UUID(), nullable=False),
        sa.Column("module_name", sa.String(length=100), nullable=False),
        sa.Column("page_name", sa.String(length=150), nullable=False),
        sa.Column("route_name", sa.String(length=150), nullable=False),
        sa.Column("url_path", sa.String(length=500), nullable=False),
        sa.Column("http_method", sa.String(length=10), nullable=True),
        sa.Column("access_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_session_id"], ["tblt_user_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tblt_user_page_access_logs_user_session_id"),
        "tblt_user_page_access_logs",
        ["user_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tblt_user_page_access_logs_user_session_id"),
        table_name="tblt_user_page_access_logs",
    )
    op.drop_table("tblt_user_page_access_logs")
    op.drop_table("tblm_user_role")
    op.drop_table("tblm_user_request_log_summaries")
    op.drop_table("tblm_role_groups")
    op.drop_index(
        op.f("ix_tblt_user_sessions_user_id"), table_name="tblt_user_sessions"
    )
    op.drop_table("tblt_user_sessions")
    op.drop_table("tblm_roles")
    op.drop_table("tblm_feature_requests")
    op.drop_table("tblm_users")
    op.drop_table("tblm_task_run")
    op.drop_table("tblm_impersonation_sandbox_records")
    op.drop_index(
        op.f("ix_tblm_impersonation_audit_impersonation_id"),
        table_name="tblm_impersonation_audit",
    )
    op.drop_table("tblm_impersonation_audit")
    op.drop_table("tblm_app_configurations")
    # ### end Alembic commands ###

    # Postgres ENUM types are separate named objects, not part of the column
    # they're used on — dropping the table doesn't drop them, so without this
    # they'd leak on every downgrade and break upgrade()/downgrade() symmetry.
    # Must run after every table using them above has already been dropped.
    sa.Enum(name="task_run_status").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="task_run_log_retention_status").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="feature_request_status").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="feature_request_priority").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="login_source").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="session_status").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="role_group_permission").drop(op.get_bind(), checkfirst=False)
